apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobber-notification
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobber-notification
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25% 
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: jobber-notification
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - jobber-notification
              topologyKey: kubernetes.io/hostname
      containers:
      - name: jobber-notification
        image: kevin1208/jobber-notification:stable
        imagePullPolicy: Always
        resources:
          limits:
            cpu: '0.5'
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 150Mi
        ports:
        - name: notification
          containerPort: 4002
        readinessProbe:
          httpGet:
            path: /notification-health
            port: 4002
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /notification-health
            port: 4002
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        env:
          - name: ENABLE_APM
            value: '1'
          - name: NODE_ENV
            value: 'production'
          - name: CLIENT_URL
            value: 'http://localhost:3000'
          - name: RABBITMQ_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: jobber-backend-secret
                key: jobber-rabbitmq-endpoint
          - name: SENDER_EMAIL
            valueFrom:
              secretKeyRef:
                name: jobber-backend-secret
                key: sender-email
          - name: SENDER_EMAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: jobber-backend-secret
                key: sender-email-password
          - name: ELASTIC_SEARCH_URL
            valueFrom:
              secretKeyRef:
                name: jobber-backend-secret
                key: jobber-elasticsearch-url
          - name: ELASTIC_APM_SERVER_URL
            valueFrom:
              secretKeyRef:
                name: jobber-backend-secret
                key:  jobber-elastic-apm-server-url
          - name: ELASTIC_APM_SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                name: jobber-backend-secret
                key: jobber-elastic-apm-secret-token