apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jobber-mongo
  namespace: production
spec:
  selector:
    matchLabels:
      app: jobber-mongo
  serviceName: jobber-mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: jobber-mongo
    spec:
      containers:
      - name: jobber-mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
          name: jobber-mongo
        resources:
          limits:
            memory: "1Gi"
            cpu: "0.5"
          requests:
            cpu: 100m
            memory: 200Mi
        readinessProbe:
          exec:
            command:
              - mongosh
              - --eval
              - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        livenessProbe:
          exec:
            command:
              - mongosh
              - --eval
              - "db.adminCommand('ping')"
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: mongo-local-storage
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-local-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: mongo-ebs-sc
      resources:
        requests:
          storage: 5Gi