apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: production
spec:
  storageClassName: mysql-ebs-sc
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce