apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: production
spec:
  storageClassName: postgres-ebs-sc
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce