apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-affinity-default
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-affinity-default
  template:
    metadata:
      labels:
        app: test-affinity-default
    spec:
      containers:
      - name: test
        image: nginx:alpine
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi

