apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-affinity-distributed
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-affinity-distributed
  template:
    metadata:
      labels:
        app: test-affinity-distributed
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - test-affinity-distributed
              topologyKey: kubernetes.io/hostname
      containers:
      - name: test
        image: nginx:alpine
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi

