apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: jobber-gateway-cron-weekend-scaledobject
  namespace: production
spec:
  scaleTargetRef:
    name: jobber-gateway
    kind: Deployment
  minReplicaCount: 0
  maxReplicaCount: 2
  triggers:
  # Horario laboral: Lunes-Viernes 08:00-20:00 (1 réplica)
  - type: cron
    metadata:
      timezone: America/Mexico_City
      start: "0 8 * * 1-5"      # 08:00 Lunes-Viernes
      end: "0 20 * * 1-5"        # 20:00 Lunes-Viernes
      desiredReplicas: "1"
  # Fines de semana: Sábado-Domingo (0 réplicas - apagado)
  - type: cron
    metadata:
      timezone: America/Mexico_City
      start: "0 0 * * 0"         # 00:00 Domingo
      end: "0 23 * * 6"          # 23:59 Sábado
      desiredReplicas: "0"
  # Noche laboral: Lunes-Viernes 20:00-08:00 (0 réplicas)
  - type: cron
    metadata:
      timezone: America/Mexico_City
      start: "0 20 * * 1-5"      # 20:00 Lunes-Viernes
      end: "0 8 * * 2-6"         # 08:00 Martes-Sábado (día siguiente)
      desiredReplicas: "0"

